# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-21 06:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servives_relation', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='initrelation',
            old_name='weigth',
            new_name='weight',
        ),
    ]
