# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-18 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_id', models.CharField(max_length=100)),
                ('api_functions', models.CharField(max_length=100)),
                ('sour_s', models.CharField(max_length=30)),
                ('dest_s', models.CharField(max_length=30)),
            ],
        ),
    ]
