# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 09:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlesv1',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='articlesv1',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articlesv1',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
